### ISSUE TITLE
Startup problems 

### ISSUE THREAD

**Issue by jackdaniels92** [nordprojects/lantern#10]
This project is really cool and I like to install it in my setup as well to use it with a Segway Robot. 

Unfortunately, I have two problems with the setup: 

1. It seems that it is not possible to run this project without an accelerometer. Is this right? 
Is there a good way to deactivate it in the code or do I have to use it? 

2. I've connected a Beamer with my Raspberry Pi 3 Model B via HDMI but it shows the error message: 
"Lantern booted in the wrong screen resolution. Make sure projector is connected". 
I'm using an Viewsonic M1 projector. With this projector I'm not able to change the resolution. I've changed the aspect ratio from "Auto" to "4:3" and "16:9" but the issue still exists. 
How can I solve this issue? 

Thanks for your help in advance.

**Comment by joerick** [comment]
Hi Jack!

Removing the accelerometer - take a look at https://github.com/nordprojects/lantern/blob/master/things/src/main/java/com/example/androidthings/lantern/App.kt#L27 - try removing the accelerometer property and then the compiler will error out where you'll need to remove references to that.

The screen resolution check is at- 
https://github.com/nordprojects/lantern/blob/master/things/src/main/java/com/example/androidthings/lantern/LaunchActivity.kt#L33 - you can probably just remove these lines and it'll work fine, except for perhaps a few layout bugs.
