### ISSUE TITLE
An unknown error occurred: 8036 

### ISSUE THREAD

**Issue by konstantinullrich** [nordprojects/lantern#12]
Hello There,

I installed the Android App using Android Studio. 
When I started the App, pressed "LOOK FOR A LANTERN" I get 
"Failed to start Nearby."
"Something went wrong, please try again"
"8036: Unknown Statuscode: 8036"
I use a Google Pixel 3 with the latest Android 10

**Comment by joerick** [comment]
Hey! 👋 Did you find a resolution?

**Comment by konstantinullrich** [comment]
No, sadly not. But I found out that Android Things is not supported anymore. Maybe th

**Comment by joerick** [comment]
It sounds like a problem with the phone/app, but I'm not sure what could be causing it. Nearby uses Wifi and Bluetooth, so it'd worth checking they're both enabled on your phone.

**Comment by konstantinullrich** [comment]
Both is enabled

**Comment by konstantinullrich** [comment]
Nearby is also not supported anymore
