### ISSUE TITLE
Interfacing with projector

### ISSUE THREAD

**Issue by vantony1** [nordprojects/lantern#14]
Hello,

I am interested in how you used ARCore with a projector and was wondering if you could point me to the file(s) where ARCore output is sent to the projector.

Thank you!

**Comment by joerick** [comment]
Hi there! I'm not sure we did use ARCore in this prototype, was it mentioned somewhere?

**Comment by vantony1** [comment]
oh, I found this project in ARCore project repos so I thought you did use ARCore. If not, my bad haha thank you for getting back to me.

**Comment by joerick** [comment]
No worries!
