### ISSUE TITLE
Build: sync error

### ISSUE THREAD

**Issue by sharmer156** [nordprojects/lantern#6]
thanks for your share. when I build: sync in the android studio, i  get this  error:
Host name 'repo.jfrog.org' does not match the certificate subject provided by the peer (CN=*.fractalanalytics.com, OU=PositiveSSL Wildcard, OU=Domain Control Validated)

**Comment by michaelcolville** [comment]
Not sure I can help with this, looks like you're having SSL problems connecting to a repo. Are you able to build other Android Studio projects? Could you try from a different connection?

Someone has reported a similar problem here https://stackoverflow.com/questions/50795894/android-gradle-isnt-see-host-name
